#!/usr/bin/env python3
"""
Builds both Expeditions Town Events Hints mods into dist/ from src/.

    python tools/build.py                # normal, publishable build
    python tools/build.py --for-upload   # same, plus what steam_workshop_upload.exe needs
    python tools/build.py --preview      # show the assembled non-English lines, build nothing

A normal build leaves dist/ containing exactly what a manual install needs and nothing
else. The game reads only the compiled .loc2 and the .darkest layout - Darkest.exe holds
zero references to *.string_table.xml - so the source XML and this script stay out of it.

The Workshop uploader is the exception: it owns localization/, deleting the .loc2 it finds
there and recompiling from *.string_table.xml. --for-upload therefore adds the XML back,
because uploading without it publishes a mod containing no strings at all.

Requires the game: localization.exe, colours/base.colours.darkest and the pristine
quest_select.layout.darkest all come from it. Adjust GAME below if your checkout moves.
"""
import argparse, glob, json, os, re, shutil, subprocess, sys, tempfile, io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
GAME = os.path.abspath(os.path.join(REPO, "..", "..", "game", "DarkestDungeon"))
ENGLISH_SRC = os.path.join(REPO, "src", "strings.english.xml")

# How far to lift the town event line, in pixels, for the International build. Longer
# translations need the room; English does not and gets no layout override at all.
LIFT_PX = 10

# The mod folder name is also the .loc2 filename prefix. Both must be underscore-only: the
# game finds a mod's strings with .*localization/[A-Za-z0-9._]+_<language>.loc2, which has
# no hyphen in its charset. A mismatch loads no strings while the mod still appears and
# enables normally in the mod menu - which looks exactly like "the mod is broken".
VARIANTS = [
    dict(name="expeditions_town_events_hints",      intl=False,
         project="project.english.xml", icon="preview_icon.english.png"),
    dict(name="expeditions_town_events_hints_intl", intl=True,
         project="project.intl.xml",    icon="preview_icon.intl.png"),
]

# The 8 events that can be granted as a quest reward, from
# campaign/town_events/town_events.quest_type_event_guarantees.json
EVENT_IDS = [
    "embark_party_buff_crypts_buff", "embark_party_buff_weald_buff",
    "embark_party_buff_cove_buff",   "embark_party_buff_warrens_buff",
    "free_abbey", "free_sanitarium", "provision_supply_free", "upgrade_tag_free_weapon",
]

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by tools/build.py - do not edit.
  English source of truth: src/strings.english.xml
-->
"""


# ---------------------------------------------------------------- string assembly

def load_strings():
    """{language: {id: text}} across every string table the game ships."""
    langs = {}
    for f in glob.glob(os.path.join(GAME, "localization", "*.string_table.xml")):
        s = open(f, encoding="utf-8", errors="replace").read()
        for lm in re.finditer(r'<language id="([^"]+)">(.*?)</language>', s, re.S):
            d = langs.setdefault(lm.group(1), {})
            for e in re.finditer(r'<entry id="([^"]+)"><!\[CDATA\[(.*?)\]\]></entry>', lm.group(2), re.S):
                d.setdefault(e.group(1), e.group(2))
    return langs


def fmt(template, *args):
    """Apply printf-style args the way the game's formatter does.

    Also strips {?token} hints, which mark a substitution point but are not rendered.
    """
    if template is None:
        return None
    t = re.sub(r'\{\?[^}]*\}', '', template).replace('%%', '\x00')
    out, i = [], 0
    for part in re.split(r'(%[+]?[ds])', t):
        if re.fullmatch(r'%[+]?[ds]', part):
            if i >= len(args):
                return None
            v = args[i]; i += 1
            if part.endswith('d'):
                v = int(round(v))
                out.append(f"{v:+d}" if '+' in part else str(v))
            else:
                out.append(str(v))
        else:
            out.append(part)
    return ''.join(out).replace('\x00', '%')


def effect_lines(event, buffs, S):
    """The effect lines for one event, in the game's own wording, deduplicated."""
    # All Saints Day frees three Abbey activities, which the game would render as three
    # separate "<room> is Free" lines - four lines with the title, one more than the
    # notification field shows in ANY language. List the rooms once and apply the wrapper a
    # single time. Vanilla vocabulary throughout; only the composition changes. Caregivers
    # Convention (two rooms) benefits from the same rule.
    activities = [d["string_data"] for d in event["data"] if d["type"] == "free_activity"]
    if len(activities) > 1:
        names = [S.get("town_activity_name_" + a) for a in activities]
        if all(names):
            joined = fmt(S.get("town_event_info_format_free_activity"), ", ".join(names))
            if joined:
                return [joined]

    lines = []
    for d in event["data"]:
        t, sd, nd = d["type"], d["string_data"], d["number_data"]
        line = None

        if t == "embark_party_buff":
            b = buffs.get(sd)
            if not b:
                continue
            key = "buff_stat_tooltip_" + b["stat_type"] + (("_" + b["stat_sub_type"]) if b.get("stat_sub_type") else "")
            stat = fmt(S.get(key), b["amount"] * 100)
            if stat and b.get("rule_type") == "in_dungeon":
                region = S.get("buff_rule_data_tooltip_" + b["rule_data"]["string"])
                stat = fmt(S.get("buff_rule_tooltip_in_dungeon"), stat, region) if region else stat
            # Deliberately NOT wrapped in town_event_info_format_embark_party_buff
            # ("%s on Next Quest"). That wrapper is what pushes these lines past the 400px
            # field in every language - French 63 chars vs 37 without it - and it is
            # redundant here, since the block already sits under "Rewards" on a quest being
            # embarked upon. English drops the same words by hand.
            #
            # The other three data types keep their wrapper: it carries the meaning
            # ("%s is Free"), not just timing.
            line = stat

        elif t == "free_activity":
            line = fmt(S.get("town_event_info_format_free_activity"), S.get("town_activity_name_" + sd))

        elif t == "provision_item_type_cost_change":
            line = fmt(S.get("town_event_info_format_provision_item_type_cost_change"),
                       S.get("str_inventory_type_name_" + sd), nd * 100)

        elif t == "upgrade_tag_free":
            line = fmt(S.get("town_event_info_format_upgrade_tag_free"),
                       S.get("upgrade_tag_name_" + sd), nd)

        # damage_low and damage_high render identically - show the line once.
        if line and line not in lines:
            lines.append(line)
    return lines


def game_data():
    events = {e["id"]: e for e in json.load(
        open(os.path.join(GAME, "campaign", "town_events", "base.town_events.events.json"),
             encoding="utf-8-sig"))["events"]}
    raw = json.load(open(os.path.join(GAME, "shared", "buffs", "base.buffs.json"), encoding="utf-8-sig"))
    buffs = {b["id"]: b for b in (raw["buffs"] if isinstance(raw, dict) else raw) if "id" in b}
    return events, buffs, load_strings()


def english_section():
    s = open(ENGLISH_SRC, encoding="utf-8").read()
    i = s.index('<language id="english">')
    return s[i:s.index("</language>", i) + len("</language>")]


def generated_sections():
    events, buffs, langs = game_data()
    out = []
    for lang in sorted(langs):
        if lang == "english":
            continue
        S = langs[lang]
        entries = []
        for eid in EVENT_IDS:
            title = S.get("town_event_title_" + eid)
            lines = effect_lines(events[eid], buffs, S)
            if not title or not lines:
                print(f"    ! {lang}/{eid}: skipped (missing title or effects)")
                continue
            # The compiler reads % as the start of a format directive and rejects the entry
            # when it is followed by '{' or a newline. Escaping to %% would compile, but
            # these titles are passed as an argument INTO other format strings rather than
            # being formatted themselves, so a %% could reach the screen literally. A
            # trailing space is invisible and keeps a single, safe %.
            body = "\n".join(l + " " if l.endswith("%") else l for l in lines)
            entries.append(
                f'    <entry id="town_event_title_{eid}"><![CDATA[{title}\n'
                f'{{colour_start|neutral}}{body}{{colour_end}}]]></entry>')
        if entries:
            out.append(f'  <language id="{lang}">\n' + "\n".join(entries) + "\n  </language>")
        print(f"    {lang:10} {len(entries)}/8 events")
    return out


def write_string_table(path, intl):
    sections = [english_section()] + (generated_sections() if intl else [])
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER + "<root>\n" + "\n\n".join(sections) + "\n</root>\n")


# ---------------------------------------------------------------- localization compile

def compile_loc2(xml, work):
    """Compile a string table to .loc2 in a throwaway sandbox, returning the outputs.

    localization.exe scans the tree named by project_paths.txt and needs a colours/ folder
    beside it to resolve {colour_start|...} tags, so it cannot simply be run in place.
    """
    for d in ("_windows/win32", "localization", "colours"):
        os.makedirs(os.path.join(work, d), exist_ok=True)
    shutil.copy(os.path.join(GAME, "_windows/win32/localization.exe"), os.path.join(work, "_windows/win32"))
    for dll in glob.glob(os.path.join(GAME, "_windows/win32/*.dll")):   # else exit 0xC0000135
        shutil.copy(dll, os.path.join(work, "_windows/win32"))
    for c in glob.glob(os.path.join(GAME, "colours/*.darkest")):
        shutil.copy(c, os.path.join(work, "colours"))
    shutil.copy(xml, os.path.join(work, "localization"))
    with open(os.path.join(work, "localization", "project_paths.txt"), "w", newline="") as f:
        f.write("..")

    r = subprocess.run([os.path.join(work, "_windows/win32/localization.exe")],
                       cwd=os.path.join(work, "localization"),
                       capture_output=True, text=True, errors="replace")
    out = (r.stdout or "") + (r.stderr or "")
    if "SUCCESS" not in out:
        print(out)
        raise SystemExit("localization.exe failed")
    built = glob.glob(os.path.join(work, "localization", "*.loc2"))
    if not built:
        raise SystemExit("no .loc2 was produced")
    return built


# ---------------------------------------------------------------- project.xml

def rescue_published_file_id(dist, src_project):
    """Move a PublishedFileId the uploader wrote into dist/ back into src/ before the wipe.

    That id IS the Workshop item. dist/ is regenerated on every build, so an id left only
    there is lost, and the next upload publishes a NEW item and orphans every subscriber.
    """
    dist_proj = os.path.join(dist, "project.xml")
    if not os.path.exists(dist_proj):
        return
    m = re.search(r'<PublishedFileId>\s*(\d+)\s*</PublishedFileId>',
                  open(dist_proj, encoding="utf-8").read())
    if not m:
        return
    pid = m.group(1)
    cur = open(src_project, encoding="utf-8", newline="").read()
    if "<PublishedFileId>" not in cur:
        eol = "\r\n" if "\r\n" in cur else "\n"
        cur = cur.replace("</project>", f"\t<PublishedFileId>{pid}</PublishedFileId>{eol}</project>")
        open(src_project, "w", encoding="utf-8", newline="").write(cur)
        print(f"    ! rescued PublishedFileId {pid} into src/{os.path.basename(src_project)} - commit this")
    elif pid not in cur:
        raise SystemExit(f"PublishedFileId mismatch: dist/ has {pid}, src/ has a different one. Resolve by hand.")


def write_project_xml(src_project, dest, dist, for_upload):
    """Copy project.xml, injecting ModDataPath only when uploading.

    ModDataPath is an absolute path to this checkout. Only steam_workshop_upload.exe needs
    it - the game does not, and a local mod loads fine with nothing but <Title> - so it is
    kept out of the committed build rather than publishing a local filesystem path.
    """
    s = open(src_project, encoding="utf-8", newline="").read()
    s = re.sub(r'[ \t]*<ModDataPath>.*?</ModDataPath>\r?\n', '', s, flags=re.S)
    if for_upload:
        path = "<ModDataPath>" + dist.replace("\\", "/") + "/</ModDataPath>"
        s, n = re.subn(r'(?m)^([ \t]*)<Title>', lambda m: f"{m.group(1)}{path}\r\n{m.group(1)}<Title>", s, count=1)
        if not n:
            raise SystemExit(f"could not inject ModDataPath into {src_project} - no <Title> element")
    open(dest, "w", encoding="utf-8", newline="").write(s)


def write_layout(dist):
    """Re-derive the lifted layout from the game's pristine file.

    Done every build rather than storing a copy, so a patch that touches
    quest_select.layout.darkest fails loudly here instead of being silently reverted for
    everyone running the mod.
    """
    rel = os.path.join("campaign", "town", "quest_select", "quest_select.layout.darkest")
    s = open(os.path.join(GAME, rel), encoding="utf-8", newline="").read()
    for old, new in ((".town_notification_icon 60 750",        f".town_notification_icon 60 {750-LIFT_PX}"),
                     (".town_notification_title_text 110 750", f".town_notification_title_text 110 {750-LIFT_PX}"),
                     (".town_notification_text 110 774",       f".town_notification_text 110 {774-LIFT_PX}")):
        if s.count(old) != 1:
            raise SystemExit(f"layout anchor {old!r} matched {s.count(old)} times - "
                             "the game file changed, re-check the offsets")
        s = s.replace(old, new)
    dest = os.path.join(dist, rel)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, "w", encoding="utf-8", newline="").write(s)


# ---------------------------------------------------------------- driver

def build(v, for_upload):
    name = v["name"]
    dist = os.path.join(REPO, "dist", name)
    src_project = os.path.join(REPO, "src", v["project"])
    print(f"=== {name}")

    rescue_published_file_id(dist, src_project)
    shutil.rmtree(dist, ignore_errors=True)
    os.makedirs(os.path.join(dist, "localization"), exist_ok=True)

    with tempfile.TemporaryDirectory(prefix=f"eteh_{name}_") as work:
        xml = os.path.join(work, f"{name}.string_table.xml")
        write_string_table(xml, v["intl"])
        for f in compile_loc2(xml, os.path.join(work, "loc")):
            shutil.copy(f, os.path.join(dist, "localization", f"{name}_{os.path.basename(f)}"))

        # The uploader OWNS localization/. It deletes the .loc2 files it finds there and
        # regenerates them from *.string_table.xml, naming the output
        # <PublishedFileId>_<language>.loc2. Upload without the XML and it deletes our
        # tables, compiles nothing, and publishes a mod with no strings at all - which is
        # exactly what happened on the first upload of both mods.
        #
        # So the XML ships for an upload run and only for an upload run. A normal build
        # leaves it out: the game itself never reads it, and the committed dist/ is meant
        # for manual installs, which need our own compiled .loc2 instead.
        if for_upload:
            shutil.copy(xml, os.path.join(dist, "localization"))

    write_project_xml(src_project, os.path.join(dist, "project.xml"), dist, for_upload)
    shutil.copy(os.path.join(REPO, "src", v["icon"]), os.path.join(dist, "preview_icon.png"))
    if v["intl"]:
        write_layout(dist)

    files = [os.path.join(r, f) for r, _, fs in os.walk(dist) for f in fs]
    kb = sum(os.path.getsize(f) for f in files) / 1024
    print(f"    {len(files)} files, {kb:,.0f} KB -> dist/{name}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--for-upload", action="store_true",
                    help="prepare dist/ for steam_workshop_upload.exe: adds ModDataPath and the "
                         "string_table.xml the uploader compiles from. Re-run plain afterwards to scrub.")
    ap.add_argument("--preview", action="store_true",
                    help="print the assembled non-English lines and exit")
    a = ap.parse_args()

    if not os.path.isdir(GAME):
        raise SystemExit(f"game not found at {GAME} - adjust GAME in this script")

    if a.preview:
        events, buffs, langs = game_data()
        for lang in sorted(langs):
            if lang == "english":
                continue
            print(f"  [{lang}]")
            for eid in EVENT_IDS:
                for l in effect_lines(events[eid], buffs, langs[lang]):
                    print(f"      {l}")
        return

    for v in VARIANTS:
        build(v, a.for_upload)


if __name__ == "__main__":
    main()
